name: Need workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print build
        run: echo 'build'

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Print test - chrome
        run: echo 'test chrome'
      - name: Print test - edge
        run: echo 'test edge'

  deploy:
    needs: [build,test]
    runs-on: ubuntu-latest
    steps:
     - name: Print deploy
       run: echo 'deploy'
